packages:
  - "services/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
