
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AnalysisTranslation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AnalysisTranslation
 * 
 */
export type AnalysisTranslationModel = runtime.Types.Result.DefaultSelection<Prisma.$AnalysisTranslationPayload>

export type AggregateAnalysisTranslation = {
  _count: AnalysisTranslationCountAggregateOutputType | null
  _min: AnalysisTranslationMinAggregateOutputType | null
  _max: AnalysisTranslationMaxAggregateOutputType | null
}

export type AnalysisTranslationMinAggregateOutputType = {
  id: string | null
  analysisId: string | null
  locale: string | null
  reasoning: string | null
  translatedAt: Date | null
}

export type AnalysisTranslationMaxAggregateOutputType = {
  id: string | null
  analysisId: string | null
  locale: string | null
  reasoning: string | null
  translatedAt: Date | null
}

export type AnalysisTranslationCountAggregateOutputType = {
  id: number
  analysisId: number
  locale: number
  reasoning: number
  positiveFactors: number
  riskFactors: number
  translatedAt: number
  _all: number
}


export type AnalysisTranslationMinAggregateInputType = {
  id?: true
  analysisId?: true
  locale?: true
  reasoning?: true
  translatedAt?: true
}

export type AnalysisTranslationMaxAggregateInputType = {
  id?: true
  analysisId?: true
  locale?: true
  reasoning?: true
  translatedAt?: true
}

export type AnalysisTranslationCountAggregateInputType = {
  id?: true
  analysisId?: true
  locale?: true
  reasoning?: true
  positiveFactors?: true
  riskFactors?: true
  translatedAt?: true
  _all?: true
}

export type AnalysisTranslationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AnalysisTranslation to aggregate.
   */
  where?: Prisma.AnalysisTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalysisTranslations to fetch.
   */
  orderBy?: Prisma.AnalysisTranslationOrderByWithRelationInput | Prisma.AnalysisTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AnalysisTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalysisTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalysisTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AnalysisTranslations
  **/
  _count?: true | AnalysisTranslationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AnalysisTranslationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AnalysisTranslationMaxAggregateInputType
}

export type GetAnalysisTranslationAggregateType<T extends AnalysisTranslationAggregateArgs> = {
      [P in keyof T & keyof AggregateAnalysisTranslation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAnalysisTranslation[P]>
    : Prisma.GetScalarType<T[P], AggregateAnalysisTranslation[P]>
}




export type AnalysisTranslationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AnalysisTranslationWhereInput
  orderBy?: Prisma.AnalysisTranslationOrderByWithAggregationInput | Prisma.AnalysisTranslationOrderByWithAggregationInput[]
  by: Prisma.AnalysisTranslationScalarFieldEnum[] | Prisma.AnalysisTranslationScalarFieldEnum
  having?: Prisma.AnalysisTranslationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AnalysisTranslationCountAggregateInputType | true
  _min?: AnalysisTranslationMinAggregateInputType
  _max?: AnalysisTranslationMaxAggregateInputType
}

export type AnalysisTranslationGroupByOutputType = {
  id: string
  analysisId: string
  locale: string
  reasoning: string | null
  positiveFactors: runtime.JsonValue | null
  riskFactors: runtime.JsonValue | null
  translatedAt: Date
  _count: AnalysisTranslationCountAggregateOutputType | null
  _min: AnalysisTranslationMinAggregateOutputType | null
  _max: AnalysisTranslationMaxAggregateOutputType | null
}

type GetAnalysisTranslationGroupByPayload<T extends AnalysisTranslationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AnalysisTranslationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AnalysisTranslationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AnalysisTranslationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AnalysisTranslationGroupByOutputType[P]>
      }
    >
  >



export type AnalysisTranslationWhereInput = {
  AND?: Prisma.AnalysisTranslationWhereInput | Prisma.AnalysisTranslationWhereInput[]
  OR?: Prisma.AnalysisTranslationWhereInput[]
  NOT?: Prisma.AnalysisTranslationWhereInput | Prisma.AnalysisTranslationWhereInput[]
  id?: Prisma.StringFilter<"AnalysisTranslation"> | string
  analysisId?: Prisma.StringFilter<"AnalysisTranslation"> | string
  locale?: Prisma.StringFilter<"AnalysisTranslation"> | string
  reasoning?: Prisma.StringNullableFilter<"AnalysisTranslation"> | string | null
  positiveFactors?: Prisma.JsonNullableFilter<"AnalysisTranslation">
  riskFactors?: Prisma.JsonNullableFilter<"AnalysisTranslation">
  translatedAt?: Prisma.DateTimeFilter<"AnalysisTranslation"> | Date | string
  analysis?: Prisma.XOR<Prisma.AnalysisRequestScalarRelationFilter, Prisma.AnalysisRequestWhereInput>
}

export type AnalysisTranslationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  analysisId?: Prisma.SortOrder
  locale?: Prisma.SortOrder
  reasoning?: Prisma.SortOrderInput | Prisma.SortOrder
  positiveFactors?: Prisma.SortOrderInput | Prisma.SortOrder
  riskFactors?: Prisma.SortOrderInput | Prisma.SortOrder
  translatedAt?: Prisma.SortOrder
  analysis?: Prisma.AnalysisRequestOrderByWithRelationInput
}

export type AnalysisTranslationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  analysisId_locale?: Prisma.AnalysisTranslationAnalysisIdLocaleCompoundUniqueInput
  AND?: Prisma.AnalysisTranslationWhereInput | Prisma.AnalysisTranslationWhereInput[]
  OR?: Prisma.AnalysisTranslationWhereInput[]
  NOT?: Prisma.AnalysisTranslationWhereInput | Prisma.AnalysisTranslationWhereInput[]
  analysisId?: Prisma.StringFilter<"AnalysisTranslation"> | string
  locale?: Prisma.StringFilter<"AnalysisTranslation"> | string
  reasoning?: Prisma.StringNullableFilter<"AnalysisTranslation"> | string | null
  positiveFactors?: Prisma.JsonNullableFilter<"AnalysisTranslation">
  riskFactors?: Prisma.JsonNullableFilter<"AnalysisTranslation">
  translatedAt?: Prisma.DateTimeFilter<"AnalysisTranslation"> | Date | string
  analysis?: Prisma.XOR<Prisma.AnalysisRequestScalarRelationFilter, Prisma.AnalysisRequestWhereInput>
}, "id" | "analysisId_locale">

export type AnalysisTranslationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  analysisId?: Prisma.SortOrder
  locale?: Prisma.SortOrder
  reasoning?: Prisma.SortOrderInput | Prisma.SortOrder
  positiveFactors?: Prisma.SortOrderInput | Prisma.SortOrder
  riskFactors?: Prisma.SortOrderInput | Prisma.SortOrder
  translatedAt?: Prisma.SortOrder
  _count?: Prisma.AnalysisTranslationCountOrderByAggregateInput
  _max?: Prisma.AnalysisTranslationMaxOrderByAggregateInput
  _min?: Prisma.AnalysisTranslationMinOrderByAggregateInput
}

export type AnalysisTranslationScalarWhereWithAggregatesInput = {
  AND?: Prisma.AnalysisTranslationScalarWhereWithAggregatesInput | Prisma.AnalysisTranslationScalarWhereWithAggregatesInput[]
  OR?: Prisma.AnalysisTranslationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AnalysisTranslationScalarWhereWithAggregatesInput | Prisma.AnalysisTranslationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AnalysisTranslation"> | string
  analysisId?: Prisma.StringWithAggregatesFilter<"AnalysisTranslation"> | string
  locale?: Prisma.StringWithAggregatesFilter<"AnalysisTranslation"> | string
  reasoning?: Prisma.StringNullableWithAggregatesFilter<"AnalysisTranslation"> | string | null
  positiveFactors?: Prisma.JsonNullableWithAggregatesFilter<"AnalysisTranslation">
  riskFactors?: Prisma.JsonNullableWithAggregatesFilter<"AnalysisTranslation">
  translatedAt?: Prisma.DateTimeWithAggregatesFilter<"AnalysisTranslation"> | Date | string
}

export type AnalysisTranslationCreateInput = {
  id?: string
  locale: string
  reasoning?: string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Date | string
  analysis: Prisma.AnalysisRequestCreateNestedOneWithoutTranslationsInput
}

export type AnalysisTranslationUncheckedCreateInput = {
  id?: string
  analysisId: string
  locale: string
  reasoning?: string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Date | string
}

export type AnalysisTranslationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  locale?: Prisma.StringFieldUpdateOperationsInput | string
  reasoning?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  analysis?: Prisma.AnalysisRequestUpdateOneRequiredWithoutTranslationsNestedInput
}

export type AnalysisTranslationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  analysisId?: Prisma.StringFieldUpdateOperationsInput | string
  locale?: Prisma.StringFieldUpdateOperationsInput | string
  reasoning?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalysisTranslationCreateManyInput = {
  id?: string
  analysisId: string
  locale: string
  reasoning?: string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Date | string
}

export type AnalysisTranslationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  locale?: Prisma.StringFieldUpdateOperationsInput | string
  reasoning?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalysisTranslationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  analysisId?: Prisma.StringFieldUpdateOperationsInput | string
  locale?: Prisma.StringFieldUpdateOperationsInput | string
  reasoning?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalysisTranslationListRelationFilter = {
  every?: Prisma.AnalysisTranslationWhereInput
  some?: Prisma.AnalysisTranslationWhereInput
  none?: Prisma.AnalysisTranslationWhereInput
}

export type AnalysisTranslationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AnalysisTranslationAnalysisIdLocaleCompoundUniqueInput = {
  analysisId: string
  locale: string
}

export type AnalysisTranslationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  analysisId?: Prisma.SortOrder
  locale?: Prisma.SortOrder
  reasoning?: Prisma.SortOrder
  positiveFactors?: Prisma.SortOrder
  riskFactors?: Prisma.SortOrder
  translatedAt?: Prisma.SortOrder
}

export type AnalysisTranslationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  analysisId?: Prisma.SortOrder
  locale?: Prisma.SortOrder
  reasoning?: Prisma.SortOrder
  translatedAt?: Prisma.SortOrder
}

export type AnalysisTranslationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  analysisId?: Prisma.SortOrder
  locale?: Prisma.SortOrder
  reasoning?: Prisma.SortOrder
  translatedAt?: Prisma.SortOrder
}

export type AnalysisTranslationCreateNestedManyWithoutAnalysisInput = {
  create?: Prisma.XOR<Prisma.AnalysisTranslationCreateWithoutAnalysisInput, Prisma.AnalysisTranslationUncheckedCreateWithoutAnalysisInput> | Prisma.AnalysisTranslationCreateWithoutAnalysisInput[] | Prisma.AnalysisTranslationUncheckedCreateWithoutAnalysisInput[]
  connectOrCreate?: Prisma.AnalysisTranslationCreateOrConnectWithoutAnalysisInput | Prisma.AnalysisTranslationCreateOrConnectWithoutAnalysisInput[]
  createMany?: Prisma.AnalysisTranslationCreateManyAnalysisInputEnvelope
  connect?: Prisma.AnalysisTranslationWhereUniqueInput | Prisma.AnalysisTranslationWhereUniqueInput[]
}

export type AnalysisTranslationUncheckedCreateNestedManyWithoutAnalysisInput = {
  create?: Prisma.XOR<Prisma.AnalysisTranslationCreateWithoutAnalysisInput, Prisma.AnalysisTranslationUncheckedCreateWithoutAnalysisInput> | Prisma.AnalysisTranslationCreateWithoutAnalysisInput[] | Prisma.AnalysisTranslationUncheckedCreateWithoutAnalysisInput[]
  connectOrCreate?: Prisma.AnalysisTranslationCreateOrConnectWithoutAnalysisInput | Prisma.AnalysisTranslationCreateOrConnectWithoutAnalysisInput[]
  createMany?: Prisma.AnalysisTranslationCreateManyAnalysisInputEnvelope
  connect?: Prisma.AnalysisTranslationWhereUniqueInput | Prisma.AnalysisTranslationWhereUniqueInput[]
}

export type AnalysisTranslationUpdateManyWithoutAnalysisNestedInput = {
  create?: Prisma.XOR<Prisma.AnalysisTranslationCreateWithoutAnalysisInput, Prisma.AnalysisTranslationUncheckedCreateWithoutAnalysisInput> | Prisma.AnalysisTranslationCreateWithoutAnalysisInput[] | Prisma.AnalysisTranslationUncheckedCreateWithoutAnalysisInput[]
  connectOrCreate?: Prisma.AnalysisTranslationCreateOrConnectWithoutAnalysisInput | Prisma.AnalysisTranslationCreateOrConnectWithoutAnalysisInput[]
  upsert?: Prisma.AnalysisTranslationUpsertWithWhereUniqueWithoutAnalysisInput | Prisma.AnalysisTranslationUpsertWithWhereUniqueWithoutAnalysisInput[]
  createMany?: Prisma.AnalysisTranslationCreateManyAnalysisInputEnvelope
  set?: Prisma.AnalysisTranslationWhereUniqueInput | Prisma.AnalysisTranslationWhereUniqueInput[]
  disconnect?: Prisma.AnalysisTranslationWhereUniqueInput | Prisma.AnalysisTranslationWhereUniqueInput[]
  delete?: Prisma.AnalysisTranslationWhereUniqueInput | Prisma.AnalysisTranslationWhereUniqueInput[]
  connect?: Prisma.AnalysisTranslationWhereUniqueInput | Prisma.AnalysisTranslationWhereUniqueInput[]
  update?: Prisma.AnalysisTranslationUpdateWithWhereUniqueWithoutAnalysisInput | Prisma.AnalysisTranslationUpdateWithWhereUniqueWithoutAnalysisInput[]
  updateMany?: Prisma.AnalysisTranslationUpdateManyWithWhereWithoutAnalysisInput | Prisma.AnalysisTranslationUpdateManyWithWhereWithoutAnalysisInput[]
  deleteMany?: Prisma.AnalysisTranslationScalarWhereInput | Prisma.AnalysisTranslationScalarWhereInput[]
}

export type AnalysisTranslationUncheckedUpdateManyWithoutAnalysisNestedInput = {
  create?: Prisma.XOR<Prisma.AnalysisTranslationCreateWithoutAnalysisInput, Prisma.AnalysisTranslationUncheckedCreateWithoutAnalysisInput> | Prisma.AnalysisTranslationCreateWithoutAnalysisInput[] | Prisma.AnalysisTranslationUncheckedCreateWithoutAnalysisInput[]
  connectOrCreate?: Prisma.AnalysisTranslationCreateOrConnectWithoutAnalysisInput | Prisma.AnalysisTranslationCreateOrConnectWithoutAnalysisInput[]
  upsert?: Prisma.AnalysisTranslationUpsertWithWhereUniqueWithoutAnalysisInput | Prisma.AnalysisTranslationUpsertWithWhereUniqueWithoutAnalysisInput[]
  createMany?: Prisma.AnalysisTranslationCreateManyAnalysisInputEnvelope
  set?: Prisma.AnalysisTranslationWhereUniqueInput | Prisma.AnalysisTranslationWhereUniqueInput[]
  disconnect?: Prisma.AnalysisTranslationWhereUniqueInput | Prisma.AnalysisTranslationWhereUniqueInput[]
  delete?: Prisma.AnalysisTranslationWhereUniqueInput | Prisma.AnalysisTranslationWhereUniqueInput[]
  connect?: Prisma.AnalysisTranslationWhereUniqueInput | Prisma.AnalysisTranslationWhereUniqueInput[]
  update?: Prisma.AnalysisTranslationUpdateWithWhereUniqueWithoutAnalysisInput | Prisma.AnalysisTranslationUpdateWithWhereUniqueWithoutAnalysisInput[]
  updateMany?: Prisma.AnalysisTranslationUpdateManyWithWhereWithoutAnalysisInput | Prisma.AnalysisTranslationUpdateManyWithWhereWithoutAnalysisInput[]
  deleteMany?: Prisma.AnalysisTranslationScalarWhereInput | Prisma.AnalysisTranslationScalarWhereInput[]
}

export type AnalysisTranslationCreateWithoutAnalysisInput = {
  id?: string
  locale: string
  reasoning?: string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Date | string
}

export type AnalysisTranslationUncheckedCreateWithoutAnalysisInput = {
  id?: string
  locale: string
  reasoning?: string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Date | string
}

export type AnalysisTranslationCreateOrConnectWithoutAnalysisInput = {
  where: Prisma.AnalysisTranslationWhereUniqueInput
  create: Prisma.XOR<Prisma.AnalysisTranslationCreateWithoutAnalysisInput, Prisma.AnalysisTranslationUncheckedCreateWithoutAnalysisInput>
}

export type AnalysisTranslationCreateManyAnalysisInputEnvelope = {
  data: Prisma.AnalysisTranslationCreateManyAnalysisInput | Prisma.AnalysisTranslationCreateManyAnalysisInput[]
  skipDuplicates?: boolean
}

export type AnalysisTranslationUpsertWithWhereUniqueWithoutAnalysisInput = {
  where: Prisma.AnalysisTranslationWhereUniqueInput
  update: Prisma.XOR<Prisma.AnalysisTranslationUpdateWithoutAnalysisInput, Prisma.AnalysisTranslationUncheckedUpdateWithoutAnalysisInput>
  create: Prisma.XOR<Prisma.AnalysisTranslationCreateWithoutAnalysisInput, Prisma.AnalysisTranslationUncheckedCreateWithoutAnalysisInput>
}

export type AnalysisTranslationUpdateWithWhereUniqueWithoutAnalysisInput = {
  where: Prisma.AnalysisTranslationWhereUniqueInput
  data: Prisma.XOR<Prisma.AnalysisTranslationUpdateWithoutAnalysisInput, Prisma.AnalysisTranslationUncheckedUpdateWithoutAnalysisInput>
}

export type AnalysisTranslationUpdateManyWithWhereWithoutAnalysisInput = {
  where: Prisma.AnalysisTranslationScalarWhereInput
  data: Prisma.XOR<Prisma.AnalysisTranslationUpdateManyMutationInput, Prisma.AnalysisTranslationUncheckedUpdateManyWithoutAnalysisInput>
}

export type AnalysisTranslationScalarWhereInput = {
  AND?: Prisma.AnalysisTranslationScalarWhereInput | Prisma.AnalysisTranslationScalarWhereInput[]
  OR?: Prisma.AnalysisTranslationScalarWhereInput[]
  NOT?: Prisma.AnalysisTranslationScalarWhereInput | Prisma.AnalysisTranslationScalarWhereInput[]
  id?: Prisma.StringFilter<"AnalysisTranslation"> | string
  analysisId?: Prisma.StringFilter<"AnalysisTranslation"> | string
  locale?: Prisma.StringFilter<"AnalysisTranslation"> | string
  reasoning?: Prisma.StringNullableFilter<"AnalysisTranslation"> | string | null
  positiveFactors?: Prisma.JsonNullableFilter<"AnalysisTranslation">
  riskFactors?: Prisma.JsonNullableFilter<"AnalysisTranslation">
  translatedAt?: Prisma.DateTimeFilter<"AnalysisTranslation"> | Date | string
}

export type AnalysisTranslationCreateManyAnalysisInput = {
  id?: string
  locale: string
  reasoning?: string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Date | string
}

export type AnalysisTranslationUpdateWithoutAnalysisInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  locale?: Prisma.StringFieldUpdateOperationsInput | string
  reasoning?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalysisTranslationUncheckedUpdateWithoutAnalysisInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  locale?: Prisma.StringFieldUpdateOperationsInput | string
  reasoning?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalysisTranslationUncheckedUpdateManyWithoutAnalysisInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  locale?: Prisma.StringFieldUpdateOperationsInput | string
  reasoning?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  positiveFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  translatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AnalysisTranslationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  analysisId?: boolean
  locale?: boolean
  reasoning?: boolean
  positiveFactors?: boolean
  riskFactors?: boolean
  translatedAt?: boolean
  analysis?: boolean | Prisma.AnalysisRequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["analysisTranslation"]>

export type AnalysisTranslationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  analysisId?: boolean
  locale?: boolean
  reasoning?: boolean
  positiveFactors?: boolean
  riskFactors?: boolean
  translatedAt?: boolean
  analysis?: boolean | Prisma.AnalysisRequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["analysisTranslation"]>

export type AnalysisTranslationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  analysisId?: boolean
  locale?: boolean
  reasoning?: boolean
  positiveFactors?: boolean
  riskFactors?: boolean
  translatedAt?: boolean
  analysis?: boolean | Prisma.AnalysisRequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["analysisTranslation"]>

export type AnalysisTranslationSelectScalar = {
  id?: boolean
  analysisId?: boolean
  locale?: boolean
  reasoning?: boolean
  positiveFactors?: boolean
  riskFactors?: boolean
  translatedAt?: boolean
}

export type AnalysisTranslationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "analysisId" | "locale" | "reasoning" | "positiveFactors" | "riskFactors" | "translatedAt", ExtArgs["result"]["analysisTranslation"]>
export type AnalysisTranslationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  analysis?: boolean | Prisma.AnalysisRequestDefaultArgs<ExtArgs>
}
export type AnalysisTranslationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  analysis?: boolean | Prisma.AnalysisRequestDefaultArgs<ExtArgs>
}
export type AnalysisTranslationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  analysis?: boolean | Prisma.AnalysisRequestDefaultArgs<ExtArgs>
}

export type $AnalysisTranslationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AnalysisTranslation"
  objects: {
    analysis: Prisma.$AnalysisRequestPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    analysisId: string
    locale: string
    reasoning: string | null
    positiveFactors: runtime.JsonValue | null
    riskFactors: runtime.JsonValue | null
    translatedAt: Date
  }, ExtArgs["result"]["analysisTranslation"]>
  composites: {}
}

export type AnalysisTranslationGetPayload<S extends boolean | null | undefined | AnalysisTranslationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AnalysisTranslationPayload, S>

export type AnalysisTranslationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AnalysisTranslationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AnalysisTranslationCountAggregateInputType | true
  }

export interface AnalysisTranslationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AnalysisTranslation'], meta: { name: 'AnalysisTranslation' } }
  /**
   * Find zero or one AnalysisTranslation that matches the filter.
   * @param {AnalysisTranslationFindUniqueArgs} args - Arguments to find a AnalysisTranslation
   * @example
   * // Get one AnalysisTranslation
   * const analysisTranslation = await prisma.analysisTranslation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AnalysisTranslationFindUniqueArgs>(args: Prisma.SelectSubset<T, AnalysisTranslationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AnalysisTranslationClient<runtime.Types.Result.GetResult<Prisma.$AnalysisTranslationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AnalysisTranslation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AnalysisTranslationFindUniqueOrThrowArgs} args - Arguments to find a AnalysisTranslation
   * @example
   * // Get one AnalysisTranslation
   * const analysisTranslation = await prisma.analysisTranslation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AnalysisTranslationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AnalysisTranslationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AnalysisTranslationClient<runtime.Types.Result.GetResult<Prisma.$AnalysisTranslationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AnalysisTranslation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisTranslationFindFirstArgs} args - Arguments to find a AnalysisTranslation
   * @example
   * // Get one AnalysisTranslation
   * const analysisTranslation = await prisma.analysisTranslation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AnalysisTranslationFindFirstArgs>(args?: Prisma.SelectSubset<T, AnalysisTranslationFindFirstArgs<ExtArgs>>): Prisma.Prisma__AnalysisTranslationClient<runtime.Types.Result.GetResult<Prisma.$AnalysisTranslationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AnalysisTranslation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisTranslationFindFirstOrThrowArgs} args - Arguments to find a AnalysisTranslation
   * @example
   * // Get one AnalysisTranslation
   * const analysisTranslation = await prisma.analysisTranslation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AnalysisTranslationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AnalysisTranslationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AnalysisTranslationClient<runtime.Types.Result.GetResult<Prisma.$AnalysisTranslationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AnalysisTranslations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisTranslationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AnalysisTranslations
   * const analysisTranslations = await prisma.analysisTranslation.findMany()
   * 
   * // Get first 10 AnalysisTranslations
   * const analysisTranslations = await prisma.analysisTranslation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const analysisTranslationWithIdOnly = await prisma.analysisTranslation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AnalysisTranslationFindManyArgs>(args?: Prisma.SelectSubset<T, AnalysisTranslationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalysisTranslationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AnalysisTranslation.
   * @param {AnalysisTranslationCreateArgs} args - Arguments to create a AnalysisTranslation.
   * @example
   * // Create one AnalysisTranslation
   * const AnalysisTranslation = await prisma.analysisTranslation.create({
   *   data: {
   *     // ... data to create a AnalysisTranslation
   *   }
   * })
   * 
   */
  create<T extends AnalysisTranslationCreateArgs>(args: Prisma.SelectSubset<T, AnalysisTranslationCreateArgs<ExtArgs>>): Prisma.Prisma__AnalysisTranslationClient<runtime.Types.Result.GetResult<Prisma.$AnalysisTranslationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AnalysisTranslations.
   * @param {AnalysisTranslationCreateManyArgs} args - Arguments to create many AnalysisTranslations.
   * @example
   * // Create many AnalysisTranslations
   * const analysisTranslation = await prisma.analysisTranslation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AnalysisTranslationCreateManyArgs>(args?: Prisma.SelectSubset<T, AnalysisTranslationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AnalysisTranslations and returns the data saved in the database.
   * @param {AnalysisTranslationCreateManyAndReturnArgs} args - Arguments to create many AnalysisTranslations.
   * @example
   * // Create many AnalysisTranslations
   * const analysisTranslation = await prisma.analysisTranslation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AnalysisTranslations and only return the `id`
   * const analysisTranslationWithIdOnly = await prisma.analysisTranslation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AnalysisTranslationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AnalysisTranslationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalysisTranslationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AnalysisTranslation.
   * @param {AnalysisTranslationDeleteArgs} args - Arguments to delete one AnalysisTranslation.
   * @example
   * // Delete one AnalysisTranslation
   * const AnalysisTranslation = await prisma.analysisTranslation.delete({
   *   where: {
   *     // ... filter to delete one AnalysisTranslation
   *   }
   * })
   * 
   */
  delete<T extends AnalysisTranslationDeleteArgs>(args: Prisma.SelectSubset<T, AnalysisTranslationDeleteArgs<ExtArgs>>): Prisma.Prisma__AnalysisTranslationClient<runtime.Types.Result.GetResult<Prisma.$AnalysisTranslationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AnalysisTranslation.
   * @param {AnalysisTranslationUpdateArgs} args - Arguments to update one AnalysisTranslation.
   * @example
   * // Update one AnalysisTranslation
   * const analysisTranslation = await prisma.analysisTranslation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AnalysisTranslationUpdateArgs>(args: Prisma.SelectSubset<T, AnalysisTranslationUpdateArgs<ExtArgs>>): Prisma.Prisma__AnalysisTranslationClient<runtime.Types.Result.GetResult<Prisma.$AnalysisTranslationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AnalysisTranslations.
   * @param {AnalysisTranslationDeleteManyArgs} args - Arguments to filter AnalysisTranslations to delete.
   * @example
   * // Delete a few AnalysisTranslations
   * const { count } = await prisma.analysisTranslation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AnalysisTranslationDeleteManyArgs>(args?: Prisma.SelectSubset<T, AnalysisTranslationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AnalysisTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisTranslationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AnalysisTranslations
   * const analysisTranslation = await prisma.analysisTranslation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AnalysisTranslationUpdateManyArgs>(args: Prisma.SelectSubset<T, AnalysisTranslationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AnalysisTranslations and returns the data updated in the database.
   * @param {AnalysisTranslationUpdateManyAndReturnArgs} args - Arguments to update many AnalysisTranslations.
   * @example
   * // Update many AnalysisTranslations
   * const analysisTranslation = await prisma.analysisTranslation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AnalysisTranslations and only return the `id`
   * const analysisTranslationWithIdOnly = await prisma.analysisTranslation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AnalysisTranslationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AnalysisTranslationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalysisTranslationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AnalysisTranslation.
   * @param {AnalysisTranslationUpsertArgs} args - Arguments to update or create a AnalysisTranslation.
   * @example
   * // Update or create a AnalysisTranslation
   * const analysisTranslation = await prisma.analysisTranslation.upsert({
   *   create: {
   *     // ... data to create a AnalysisTranslation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AnalysisTranslation we want to update
   *   }
   * })
   */
  upsert<T extends AnalysisTranslationUpsertArgs>(args: Prisma.SelectSubset<T, AnalysisTranslationUpsertArgs<ExtArgs>>): Prisma.Prisma__AnalysisTranslationClient<runtime.Types.Result.GetResult<Prisma.$AnalysisTranslationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AnalysisTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisTranslationCountArgs} args - Arguments to filter AnalysisTranslations to count.
   * @example
   * // Count the number of AnalysisTranslations
   * const count = await prisma.analysisTranslation.count({
   *   where: {
   *     // ... the filter for the AnalysisTranslations we want to count
   *   }
   * })
  **/
  count<T extends AnalysisTranslationCountArgs>(
    args?: Prisma.Subset<T, AnalysisTranslationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AnalysisTranslationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AnalysisTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisTranslationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AnalysisTranslationAggregateArgs>(args: Prisma.Subset<T, AnalysisTranslationAggregateArgs>): Prisma.PrismaPromise<GetAnalysisTranslationAggregateType<T>>

  /**
   * Group by AnalysisTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalysisTranslationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AnalysisTranslationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AnalysisTranslationGroupByArgs['orderBy'] }
      : { orderBy?: AnalysisTranslationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AnalysisTranslationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAnalysisTranslationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AnalysisTranslation model
 */
readonly fields: AnalysisTranslationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AnalysisTranslation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AnalysisTranslationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  analysis<T extends Prisma.AnalysisRequestDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AnalysisRequestDefaultArgs<ExtArgs>>): Prisma.Prisma__AnalysisRequestClient<runtime.Types.Result.GetResult<Prisma.$AnalysisRequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AnalysisTranslation model
 */
export interface AnalysisTranslationFieldRefs {
  readonly id: Prisma.FieldRef<"AnalysisTranslation", 'String'>
  readonly analysisId: Prisma.FieldRef<"AnalysisTranslation", 'String'>
  readonly locale: Prisma.FieldRef<"AnalysisTranslation", 'String'>
  readonly reasoning: Prisma.FieldRef<"AnalysisTranslation", 'String'>
  readonly positiveFactors: Prisma.FieldRef<"AnalysisTranslation", 'Json'>
  readonly riskFactors: Prisma.FieldRef<"AnalysisTranslation", 'Json'>
  readonly translatedAt: Prisma.FieldRef<"AnalysisTranslation", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AnalysisTranslation findUnique
 */
export type AnalysisTranslationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisTranslation
   */
  select?: Prisma.AnalysisTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisTranslation
   */
  omit?: Prisma.AnalysisTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisTranslationInclude<ExtArgs> | null
  /**
   * Filter, which AnalysisTranslation to fetch.
   */
  where: Prisma.AnalysisTranslationWhereUniqueInput
}

/**
 * AnalysisTranslation findUniqueOrThrow
 */
export type AnalysisTranslationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisTranslation
   */
  select?: Prisma.AnalysisTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisTranslation
   */
  omit?: Prisma.AnalysisTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisTranslationInclude<ExtArgs> | null
  /**
   * Filter, which AnalysisTranslation to fetch.
   */
  where: Prisma.AnalysisTranslationWhereUniqueInput
}

/**
 * AnalysisTranslation findFirst
 */
export type AnalysisTranslationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisTranslation
   */
  select?: Prisma.AnalysisTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisTranslation
   */
  omit?: Prisma.AnalysisTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisTranslationInclude<ExtArgs> | null
  /**
   * Filter, which AnalysisTranslation to fetch.
   */
  where?: Prisma.AnalysisTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalysisTranslations to fetch.
   */
  orderBy?: Prisma.AnalysisTranslationOrderByWithRelationInput | Prisma.AnalysisTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AnalysisTranslations.
   */
  cursor?: Prisma.AnalysisTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalysisTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalysisTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AnalysisTranslations.
   */
  distinct?: Prisma.AnalysisTranslationScalarFieldEnum | Prisma.AnalysisTranslationScalarFieldEnum[]
}

/**
 * AnalysisTranslation findFirstOrThrow
 */
export type AnalysisTranslationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisTranslation
   */
  select?: Prisma.AnalysisTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisTranslation
   */
  omit?: Prisma.AnalysisTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisTranslationInclude<ExtArgs> | null
  /**
   * Filter, which AnalysisTranslation to fetch.
   */
  where?: Prisma.AnalysisTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalysisTranslations to fetch.
   */
  orderBy?: Prisma.AnalysisTranslationOrderByWithRelationInput | Prisma.AnalysisTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AnalysisTranslations.
   */
  cursor?: Prisma.AnalysisTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalysisTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalysisTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AnalysisTranslations.
   */
  distinct?: Prisma.AnalysisTranslationScalarFieldEnum | Prisma.AnalysisTranslationScalarFieldEnum[]
}

/**
 * AnalysisTranslation findMany
 */
export type AnalysisTranslationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisTranslation
   */
  select?: Prisma.AnalysisTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisTranslation
   */
  omit?: Prisma.AnalysisTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisTranslationInclude<ExtArgs> | null
  /**
   * Filter, which AnalysisTranslations to fetch.
   */
  where?: Prisma.AnalysisTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalysisTranslations to fetch.
   */
  orderBy?: Prisma.AnalysisTranslationOrderByWithRelationInput | Prisma.AnalysisTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AnalysisTranslations.
   */
  cursor?: Prisma.AnalysisTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalysisTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalysisTranslations.
   */
  skip?: number
  distinct?: Prisma.AnalysisTranslationScalarFieldEnum | Prisma.AnalysisTranslationScalarFieldEnum[]
}

/**
 * AnalysisTranslation create
 */
export type AnalysisTranslationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisTranslation
   */
  select?: Prisma.AnalysisTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisTranslation
   */
  omit?: Prisma.AnalysisTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisTranslationInclude<ExtArgs> | null
  /**
   * The data needed to create a AnalysisTranslation.
   */
  data: Prisma.XOR<Prisma.AnalysisTranslationCreateInput, Prisma.AnalysisTranslationUncheckedCreateInput>
}

/**
 * AnalysisTranslation createMany
 */
export type AnalysisTranslationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AnalysisTranslations.
   */
  data: Prisma.AnalysisTranslationCreateManyInput | Prisma.AnalysisTranslationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AnalysisTranslation createManyAndReturn
 */
export type AnalysisTranslationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisTranslation
   */
  select?: Prisma.AnalysisTranslationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisTranslation
   */
  omit?: Prisma.AnalysisTranslationOmit<ExtArgs> | null
  /**
   * The data used to create many AnalysisTranslations.
   */
  data: Prisma.AnalysisTranslationCreateManyInput | Prisma.AnalysisTranslationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisTranslationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AnalysisTranslation update
 */
export type AnalysisTranslationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisTranslation
   */
  select?: Prisma.AnalysisTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisTranslation
   */
  omit?: Prisma.AnalysisTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisTranslationInclude<ExtArgs> | null
  /**
   * The data needed to update a AnalysisTranslation.
   */
  data: Prisma.XOR<Prisma.AnalysisTranslationUpdateInput, Prisma.AnalysisTranslationUncheckedUpdateInput>
  /**
   * Choose, which AnalysisTranslation to update.
   */
  where: Prisma.AnalysisTranslationWhereUniqueInput
}

/**
 * AnalysisTranslation updateMany
 */
export type AnalysisTranslationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AnalysisTranslations.
   */
  data: Prisma.XOR<Prisma.AnalysisTranslationUpdateManyMutationInput, Prisma.AnalysisTranslationUncheckedUpdateManyInput>
  /**
   * Filter which AnalysisTranslations to update
   */
  where?: Prisma.AnalysisTranslationWhereInput
  /**
   * Limit how many AnalysisTranslations to update.
   */
  limit?: number
}

/**
 * AnalysisTranslation updateManyAndReturn
 */
export type AnalysisTranslationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisTranslation
   */
  select?: Prisma.AnalysisTranslationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisTranslation
   */
  omit?: Prisma.AnalysisTranslationOmit<ExtArgs> | null
  /**
   * The data used to update AnalysisTranslations.
   */
  data: Prisma.XOR<Prisma.AnalysisTranslationUpdateManyMutationInput, Prisma.AnalysisTranslationUncheckedUpdateManyInput>
  /**
   * Filter which AnalysisTranslations to update
   */
  where?: Prisma.AnalysisTranslationWhereInput
  /**
   * Limit how many AnalysisTranslations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisTranslationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AnalysisTranslation upsert
 */
export type AnalysisTranslationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisTranslation
   */
  select?: Prisma.AnalysisTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisTranslation
   */
  omit?: Prisma.AnalysisTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisTranslationInclude<ExtArgs> | null
  /**
   * The filter to search for the AnalysisTranslation to update in case it exists.
   */
  where: Prisma.AnalysisTranslationWhereUniqueInput
  /**
   * In case the AnalysisTranslation found by the `where` argument doesn't exist, create a new AnalysisTranslation with this data.
   */
  create: Prisma.XOR<Prisma.AnalysisTranslationCreateInput, Prisma.AnalysisTranslationUncheckedCreateInput>
  /**
   * In case the AnalysisTranslation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AnalysisTranslationUpdateInput, Prisma.AnalysisTranslationUncheckedUpdateInput>
}

/**
 * AnalysisTranslation delete
 */
export type AnalysisTranslationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisTranslation
   */
  select?: Prisma.AnalysisTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisTranslation
   */
  omit?: Prisma.AnalysisTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisTranslationInclude<ExtArgs> | null
  /**
   * Filter which AnalysisTranslation to delete.
   */
  where: Prisma.AnalysisTranslationWhereUniqueInput
}

/**
 * AnalysisTranslation deleteMany
 */
export type AnalysisTranslationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AnalysisTranslations to delete
   */
  where?: Prisma.AnalysisTranslationWhereInput
  /**
   * Limit how many AnalysisTranslations to delete.
   */
  limit?: number
}

/**
 * AnalysisTranslation without action
 */
export type AnalysisTranslationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalysisTranslation
   */
  select?: Prisma.AnalysisTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalysisTranslation
   */
  omit?: Prisma.AnalysisTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalysisTranslationInclude<ExtArgs> | null
}
