
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProcessedData` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProcessedData
 * 
 */
export type ProcessedDataModel = runtime.Types.Result.DefaultSelection<Prisma.$ProcessedDataPayload>

export type AggregateProcessedData = {
  _count: ProcessedDataCountAggregateOutputType | null
  _avg: ProcessedDataAvgAggregateOutputType | null
  _sum: ProcessedDataSumAggregateOutputType | null
  _min: ProcessedDataMinAggregateOutputType | null
  _max: ProcessedDataMaxAggregateOutputType | null
}

export type ProcessedDataAvgAggregateOutputType = {
  score: number | null
  confidence: number | null
  tokensUsed: number | null
  cost: number | null
  inferenceDurationMs: number | null
}

export type ProcessedDataSumAggregateOutputType = {
  score: number | null
  confidence: number | null
  tokensUsed: number | null
  cost: number | null
  inferenceDurationMs: number | null
}

export type ProcessedDataMinAggregateOutputType = {
  id: string | null
  analysisRequestId: string | null
  userId: string | null
  chain: string | null
  address: string | null
  score: number | null
  confidence: number | null
  reasoning: string | null
  modelVersion: string | null
  promptVersion: string | null
  tokensUsed: number | null
  cost: number | null
  inferenceDurationMs: number | null
  walletContextHash: string | null
  validUntil: Date | null
  createdAt: Date | null
}

export type ProcessedDataMaxAggregateOutputType = {
  id: string | null
  analysisRequestId: string | null
  userId: string | null
  chain: string | null
  address: string | null
  score: number | null
  confidence: number | null
  reasoning: string | null
  modelVersion: string | null
  promptVersion: string | null
  tokensUsed: number | null
  cost: number | null
  inferenceDurationMs: number | null
  walletContextHash: string | null
  validUntil: Date | null
  createdAt: Date | null
}

export type ProcessedDataCountAggregateOutputType = {
  id: number
  analysisRequestId: number
  userId: number
  chain: number
  address: number
  score: number
  confidence: number
  reasoning: number
  positiveFactors: number
  riskFactors: number
  modelVersion: number
  promptVersion: number
  tokensUsed: number
  cost: number
  inferenceDurationMs: number
  walletContextHash: number
  validUntil: number
  createdAt: number
  _all: number
}


export type ProcessedDataAvgAggregateInputType = {
  score?: true
  confidence?: true
  tokensUsed?: true
  cost?: true
  inferenceDurationMs?: true
}

export type ProcessedDataSumAggregateInputType = {
  score?: true
  confidence?: true
  tokensUsed?: true
  cost?: true
  inferenceDurationMs?: true
}

export type ProcessedDataMinAggregateInputType = {
  id?: true
  analysisRequestId?: true
  userId?: true
  chain?: true
  address?: true
  score?: true
  confidence?: true
  reasoning?: true
  modelVersion?: true
  promptVersion?: true
  tokensUsed?: true
  cost?: true
  inferenceDurationMs?: true
  walletContextHash?: true
  validUntil?: true
  createdAt?: true
}

export type ProcessedDataMaxAggregateInputType = {
  id?: true
  analysisRequestId?: true
  userId?: true
  chain?: true
  address?: true
  score?: true
  confidence?: true
  reasoning?: true
  modelVersion?: true
  promptVersion?: true
  tokensUsed?: true
  cost?: true
  inferenceDurationMs?: true
  walletContextHash?: true
  validUntil?: true
  createdAt?: true
}

export type ProcessedDataCountAggregateInputType = {
  id?: true
  analysisRequestId?: true
  userId?: true
  chain?: true
  address?: true
  score?: true
  confidence?: true
  reasoning?: true
  positiveFactors?: true
  riskFactors?: true
  modelVersion?: true
  promptVersion?: true
  tokensUsed?: true
  cost?: true
  inferenceDurationMs?: true
  walletContextHash?: true
  validUntil?: true
  createdAt?: true
  _all?: true
}

export type ProcessedDataAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProcessedData to aggregate.
   */
  where?: Prisma.ProcessedDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProcessedData to fetch.
   */
  orderBy?: Prisma.ProcessedDataOrderByWithRelationInput | Prisma.ProcessedDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProcessedDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProcessedData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProcessedData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProcessedData
  **/
  _count?: true | ProcessedDataCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProcessedDataAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProcessedDataSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProcessedDataMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProcessedDataMaxAggregateInputType
}

export type GetProcessedDataAggregateType<T extends ProcessedDataAggregateArgs> = {
      [P in keyof T & keyof AggregateProcessedData]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProcessedData[P]>
    : Prisma.GetScalarType<T[P], AggregateProcessedData[P]>
}




export type ProcessedDataGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProcessedDataWhereInput
  orderBy?: Prisma.ProcessedDataOrderByWithAggregationInput | Prisma.ProcessedDataOrderByWithAggregationInput[]
  by: Prisma.ProcessedDataScalarFieldEnum[] | Prisma.ProcessedDataScalarFieldEnum
  having?: Prisma.ProcessedDataScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProcessedDataCountAggregateInputType | true
  _avg?: ProcessedDataAvgAggregateInputType
  _sum?: ProcessedDataSumAggregateInputType
  _min?: ProcessedDataMinAggregateInputType
  _max?: ProcessedDataMaxAggregateInputType
}

export type ProcessedDataGroupByOutputType = {
  id: string
  analysisRequestId: string
  userId: string
  chain: string
  address: string
  score: number
  confidence: number
  reasoning: string
  positiveFactors: runtime.JsonValue
  riskFactors: runtime.JsonValue
  modelVersion: string
  promptVersion: string
  tokensUsed: number
  cost: number
  inferenceDurationMs: number
  walletContextHash: string
  validUntil: Date
  createdAt: Date
  _count: ProcessedDataCountAggregateOutputType | null
  _avg: ProcessedDataAvgAggregateOutputType | null
  _sum: ProcessedDataSumAggregateOutputType | null
  _min: ProcessedDataMinAggregateOutputType | null
  _max: ProcessedDataMaxAggregateOutputType | null
}

type GetProcessedDataGroupByPayload<T extends ProcessedDataGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProcessedDataGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProcessedDataGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProcessedDataGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProcessedDataGroupByOutputType[P]>
      }
    >
  >



export type ProcessedDataWhereInput = {
  AND?: Prisma.ProcessedDataWhereInput | Prisma.ProcessedDataWhereInput[]
  OR?: Prisma.ProcessedDataWhereInput[]
  NOT?: Prisma.ProcessedDataWhereInput | Prisma.ProcessedDataWhereInput[]
  id?: Prisma.StringFilter<"ProcessedData"> | string
  analysisRequestId?: Prisma.StringFilter<"ProcessedData"> | string
  userId?: Prisma.StringFilter<"ProcessedData"> | string
  chain?: Prisma.StringFilter<"ProcessedData"> | string
  address?: Prisma.StringFilter<"ProcessedData"> | string
  score?: Prisma.IntFilter<"ProcessedData"> | number
  confidence?: Prisma.FloatFilter<"ProcessedData"> | number
  reasoning?: Prisma.StringFilter<"ProcessedData"> | string
  positiveFactors?: Prisma.JsonFilter<"ProcessedData">
  riskFactors?: Prisma.JsonFilter<"ProcessedData">
  modelVersion?: Prisma.StringFilter<"ProcessedData"> | string
  promptVersion?: Prisma.StringFilter<"ProcessedData"> | string
  tokensUsed?: Prisma.IntFilter<"ProcessedData"> | number
  cost?: Prisma.FloatFilter<"ProcessedData"> | number
  inferenceDurationMs?: Prisma.IntFilter<"ProcessedData"> | number
  walletContextHash?: Prisma.StringFilter<"ProcessedData"> | string
  validUntil?: Prisma.DateTimeFilter<"ProcessedData"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ProcessedData"> | Date | string
}

export type ProcessedDataOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  analysisRequestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chain?: Prisma.SortOrder
  address?: Prisma.SortOrder
  score?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  reasoning?: Prisma.SortOrder
  positiveFactors?: Prisma.SortOrder
  riskFactors?: Prisma.SortOrder
  modelVersion?: Prisma.SortOrder
  promptVersion?: Prisma.SortOrder
  tokensUsed?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  inferenceDurationMs?: Prisma.SortOrder
  walletContextHash?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProcessedDataWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ProcessedDataWhereInput | Prisma.ProcessedDataWhereInput[]
  OR?: Prisma.ProcessedDataWhereInput[]
  NOT?: Prisma.ProcessedDataWhereInput | Prisma.ProcessedDataWhereInput[]
  analysisRequestId?: Prisma.StringFilter<"ProcessedData"> | string
  userId?: Prisma.StringFilter<"ProcessedData"> | string
  chain?: Prisma.StringFilter<"ProcessedData"> | string
  address?: Prisma.StringFilter<"ProcessedData"> | string
  score?: Prisma.IntFilter<"ProcessedData"> | number
  confidence?: Prisma.FloatFilter<"ProcessedData"> | number
  reasoning?: Prisma.StringFilter<"ProcessedData"> | string
  positiveFactors?: Prisma.JsonFilter<"ProcessedData">
  riskFactors?: Prisma.JsonFilter<"ProcessedData">
  modelVersion?: Prisma.StringFilter<"ProcessedData"> | string
  promptVersion?: Prisma.StringFilter<"ProcessedData"> | string
  tokensUsed?: Prisma.IntFilter<"ProcessedData"> | number
  cost?: Prisma.FloatFilter<"ProcessedData"> | number
  inferenceDurationMs?: Prisma.IntFilter<"ProcessedData"> | number
  walletContextHash?: Prisma.StringFilter<"ProcessedData"> | string
  validUntil?: Prisma.DateTimeFilter<"ProcessedData"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ProcessedData"> | Date | string
}, "id">

export type ProcessedDataOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  analysisRequestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chain?: Prisma.SortOrder
  address?: Prisma.SortOrder
  score?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  reasoning?: Prisma.SortOrder
  positiveFactors?: Prisma.SortOrder
  riskFactors?: Prisma.SortOrder
  modelVersion?: Prisma.SortOrder
  promptVersion?: Prisma.SortOrder
  tokensUsed?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  inferenceDurationMs?: Prisma.SortOrder
  walletContextHash?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ProcessedDataCountOrderByAggregateInput
  _avg?: Prisma.ProcessedDataAvgOrderByAggregateInput
  _max?: Prisma.ProcessedDataMaxOrderByAggregateInput
  _min?: Prisma.ProcessedDataMinOrderByAggregateInput
  _sum?: Prisma.ProcessedDataSumOrderByAggregateInput
}

export type ProcessedDataScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProcessedDataScalarWhereWithAggregatesInput | Prisma.ProcessedDataScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProcessedDataScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProcessedDataScalarWhereWithAggregatesInput | Prisma.ProcessedDataScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProcessedData"> | string
  analysisRequestId?: Prisma.StringWithAggregatesFilter<"ProcessedData"> | string
  userId?: Prisma.StringWithAggregatesFilter<"ProcessedData"> | string
  chain?: Prisma.StringWithAggregatesFilter<"ProcessedData"> | string
  address?: Prisma.StringWithAggregatesFilter<"ProcessedData"> | string
  score?: Prisma.IntWithAggregatesFilter<"ProcessedData"> | number
  confidence?: Prisma.FloatWithAggregatesFilter<"ProcessedData"> | number
  reasoning?: Prisma.StringWithAggregatesFilter<"ProcessedData"> | string
  positiveFactors?: Prisma.JsonWithAggregatesFilter<"ProcessedData">
  riskFactors?: Prisma.JsonWithAggregatesFilter<"ProcessedData">
  modelVersion?: Prisma.StringWithAggregatesFilter<"ProcessedData"> | string
  promptVersion?: Prisma.StringWithAggregatesFilter<"ProcessedData"> | string
  tokensUsed?: Prisma.IntWithAggregatesFilter<"ProcessedData"> | number
  cost?: Prisma.FloatWithAggregatesFilter<"ProcessedData"> | number
  inferenceDurationMs?: Prisma.IntWithAggregatesFilter<"ProcessedData"> | number
  walletContextHash?: Prisma.StringWithAggregatesFilter<"ProcessedData"> | string
  validUntil?: Prisma.DateTimeWithAggregatesFilter<"ProcessedData"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ProcessedData"> | Date | string
}

export type ProcessedDataCreateInput = {
  id?: string
  analysisRequestId: string
  userId: string
  chain: string
  address: string
  score: number
  confidence: number
  reasoning: string
  positiveFactors: Prisma.JsonNullValueInput | runtime.InputJsonValue
  riskFactors: Prisma.JsonNullValueInput | runtime.InputJsonValue
  modelVersion: string
  promptVersion: string
  tokensUsed: number
  cost: number
  inferenceDurationMs: number
  walletContextHash: string
  validUntil: Date | string
  createdAt?: Date | string
}

export type ProcessedDataUncheckedCreateInput = {
  id?: string
  analysisRequestId: string
  userId: string
  chain: string
  address: string
  score: number
  confidence: number
  reasoning: string
  positiveFactors: Prisma.JsonNullValueInput | runtime.InputJsonValue
  riskFactors: Prisma.JsonNullValueInput | runtime.InputJsonValue
  modelVersion: string
  promptVersion: string
  tokensUsed: number
  cost: number
  inferenceDurationMs: number
  walletContextHash: string
  validUntil: Date | string
  createdAt?: Date | string
}

export type ProcessedDataUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  analysisRequestId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  chain?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  reasoning?: Prisma.StringFieldUpdateOperationsInput | string
  positiveFactors?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  modelVersion?: Prisma.StringFieldUpdateOperationsInput | string
  promptVersion?: Prisma.StringFieldUpdateOperationsInput | string
  tokensUsed?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.FloatFieldUpdateOperationsInput | number
  inferenceDurationMs?: Prisma.IntFieldUpdateOperationsInput | number
  walletContextHash?: Prisma.StringFieldUpdateOperationsInput | string
  validUntil?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProcessedDataUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  analysisRequestId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  chain?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  reasoning?: Prisma.StringFieldUpdateOperationsInput | string
  positiveFactors?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  modelVersion?: Prisma.StringFieldUpdateOperationsInput | string
  promptVersion?: Prisma.StringFieldUpdateOperationsInput | string
  tokensUsed?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.FloatFieldUpdateOperationsInput | number
  inferenceDurationMs?: Prisma.IntFieldUpdateOperationsInput | number
  walletContextHash?: Prisma.StringFieldUpdateOperationsInput | string
  validUntil?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProcessedDataCreateManyInput = {
  id?: string
  analysisRequestId: string
  userId: string
  chain: string
  address: string
  score: number
  confidence: number
  reasoning: string
  positiveFactors: Prisma.JsonNullValueInput | runtime.InputJsonValue
  riskFactors: Prisma.JsonNullValueInput | runtime.InputJsonValue
  modelVersion: string
  promptVersion: string
  tokensUsed: number
  cost: number
  inferenceDurationMs: number
  walletContextHash: string
  validUntil: Date | string
  createdAt?: Date | string
}

export type ProcessedDataUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  analysisRequestId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  chain?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  reasoning?: Prisma.StringFieldUpdateOperationsInput | string
  positiveFactors?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  modelVersion?: Prisma.StringFieldUpdateOperationsInput | string
  promptVersion?: Prisma.StringFieldUpdateOperationsInput | string
  tokensUsed?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.FloatFieldUpdateOperationsInput | number
  inferenceDurationMs?: Prisma.IntFieldUpdateOperationsInput | number
  walletContextHash?: Prisma.StringFieldUpdateOperationsInput | string
  validUntil?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProcessedDataUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  analysisRequestId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  chain?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  reasoning?: Prisma.StringFieldUpdateOperationsInput | string
  positiveFactors?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  riskFactors?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  modelVersion?: Prisma.StringFieldUpdateOperationsInput | string
  promptVersion?: Prisma.StringFieldUpdateOperationsInput | string
  tokensUsed?: Prisma.IntFieldUpdateOperationsInput | number
  cost?: Prisma.FloatFieldUpdateOperationsInput | number
  inferenceDurationMs?: Prisma.IntFieldUpdateOperationsInput | number
  walletContextHash?: Prisma.StringFieldUpdateOperationsInput | string
  validUntil?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProcessedDataCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  analysisRequestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chain?: Prisma.SortOrder
  address?: Prisma.SortOrder
  score?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  reasoning?: Prisma.SortOrder
  positiveFactors?: Prisma.SortOrder
  riskFactors?: Prisma.SortOrder
  modelVersion?: Prisma.SortOrder
  promptVersion?: Prisma.SortOrder
  tokensUsed?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  inferenceDurationMs?: Prisma.SortOrder
  walletContextHash?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProcessedDataAvgOrderByAggregateInput = {
  score?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  tokensUsed?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  inferenceDurationMs?: Prisma.SortOrder
}

export type ProcessedDataMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  analysisRequestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chain?: Prisma.SortOrder
  address?: Prisma.SortOrder
  score?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  reasoning?: Prisma.SortOrder
  modelVersion?: Prisma.SortOrder
  promptVersion?: Prisma.SortOrder
  tokensUsed?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  inferenceDurationMs?: Prisma.SortOrder
  walletContextHash?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProcessedDataMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  analysisRequestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  chain?: Prisma.SortOrder
  address?: Prisma.SortOrder
  score?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  reasoning?: Prisma.SortOrder
  modelVersion?: Prisma.SortOrder
  promptVersion?: Prisma.SortOrder
  tokensUsed?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  inferenceDurationMs?: Prisma.SortOrder
  walletContextHash?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProcessedDataSumOrderByAggregateInput = {
  score?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  tokensUsed?: Prisma.SortOrder
  cost?: Prisma.SortOrder
  inferenceDurationMs?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type ProcessedDataSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  analysisRequestId?: boolean
  userId?: boolean
  chain?: boolean
  address?: boolean
  score?: boolean
  confidence?: boolean
  reasoning?: boolean
  positiveFactors?: boolean
  riskFactors?: boolean
  modelVersion?: boolean
  promptVersion?: boolean
  tokensUsed?: boolean
  cost?: boolean
  inferenceDurationMs?: boolean
  walletContextHash?: boolean
  validUntil?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["processedData"]>

export type ProcessedDataSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  analysisRequestId?: boolean
  userId?: boolean
  chain?: boolean
  address?: boolean
  score?: boolean
  confidence?: boolean
  reasoning?: boolean
  positiveFactors?: boolean
  riskFactors?: boolean
  modelVersion?: boolean
  promptVersion?: boolean
  tokensUsed?: boolean
  cost?: boolean
  inferenceDurationMs?: boolean
  walletContextHash?: boolean
  validUntil?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["processedData"]>

export type ProcessedDataSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  analysisRequestId?: boolean
  userId?: boolean
  chain?: boolean
  address?: boolean
  score?: boolean
  confidence?: boolean
  reasoning?: boolean
  positiveFactors?: boolean
  riskFactors?: boolean
  modelVersion?: boolean
  promptVersion?: boolean
  tokensUsed?: boolean
  cost?: boolean
  inferenceDurationMs?: boolean
  walletContextHash?: boolean
  validUntil?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["processedData"]>

export type ProcessedDataSelectScalar = {
  id?: boolean
  analysisRequestId?: boolean
  userId?: boolean
  chain?: boolean
  address?: boolean
  score?: boolean
  confidence?: boolean
  reasoning?: boolean
  positiveFactors?: boolean
  riskFactors?: boolean
  modelVersion?: boolean
  promptVersion?: boolean
  tokensUsed?: boolean
  cost?: boolean
  inferenceDurationMs?: boolean
  walletContextHash?: boolean
  validUntil?: boolean
  createdAt?: boolean
}

export type ProcessedDataOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "analysisRequestId" | "userId" | "chain" | "address" | "score" | "confidence" | "reasoning" | "positiveFactors" | "riskFactors" | "modelVersion" | "promptVersion" | "tokensUsed" | "cost" | "inferenceDurationMs" | "walletContextHash" | "validUntil" | "createdAt", ExtArgs["result"]["processedData"]>

export type $ProcessedDataPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProcessedData"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    analysisRequestId: string
    userId: string
    chain: string
    address: string
    score: number
    confidence: number
    reasoning: string
    positiveFactors: runtime.JsonValue
    riskFactors: runtime.JsonValue
    modelVersion: string
    promptVersion: string
    tokensUsed: number
    cost: number
    inferenceDurationMs: number
    walletContextHash: string
    validUntil: Date
    createdAt: Date
  }, ExtArgs["result"]["processedData"]>
  composites: {}
}

export type ProcessedDataGetPayload<S extends boolean | null | undefined | ProcessedDataDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProcessedDataPayload, S>

export type ProcessedDataCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProcessedDataFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProcessedDataCountAggregateInputType | true
  }

export interface ProcessedDataDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProcessedData'], meta: { name: 'ProcessedData' } }
  /**
   * Find zero or one ProcessedData that matches the filter.
   * @param {ProcessedDataFindUniqueArgs} args - Arguments to find a ProcessedData
   * @example
   * // Get one ProcessedData
   * const processedData = await prisma.processedData.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProcessedDataFindUniqueArgs>(args: Prisma.SelectSubset<T, ProcessedDataFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProcessedDataClient<runtime.Types.Result.GetResult<Prisma.$ProcessedDataPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProcessedData that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProcessedDataFindUniqueOrThrowArgs} args - Arguments to find a ProcessedData
   * @example
   * // Get one ProcessedData
   * const processedData = await prisma.processedData.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProcessedDataFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProcessedDataFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProcessedDataClient<runtime.Types.Result.GetResult<Prisma.$ProcessedDataPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProcessedData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcessedDataFindFirstArgs} args - Arguments to find a ProcessedData
   * @example
   * // Get one ProcessedData
   * const processedData = await prisma.processedData.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProcessedDataFindFirstArgs>(args?: Prisma.SelectSubset<T, ProcessedDataFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProcessedDataClient<runtime.Types.Result.GetResult<Prisma.$ProcessedDataPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProcessedData that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcessedDataFindFirstOrThrowArgs} args - Arguments to find a ProcessedData
   * @example
   * // Get one ProcessedData
   * const processedData = await prisma.processedData.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProcessedDataFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProcessedDataFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProcessedDataClient<runtime.Types.Result.GetResult<Prisma.$ProcessedDataPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProcessedData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcessedDataFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProcessedData
   * const processedData = await prisma.processedData.findMany()
   * 
   * // Get first 10 ProcessedData
   * const processedData = await prisma.processedData.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const processedDataWithIdOnly = await prisma.processedData.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProcessedDataFindManyArgs>(args?: Prisma.SelectSubset<T, ProcessedDataFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProcessedDataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProcessedData.
   * @param {ProcessedDataCreateArgs} args - Arguments to create a ProcessedData.
   * @example
   * // Create one ProcessedData
   * const ProcessedData = await prisma.processedData.create({
   *   data: {
   *     // ... data to create a ProcessedData
   *   }
   * })
   * 
   */
  create<T extends ProcessedDataCreateArgs>(args: Prisma.SelectSubset<T, ProcessedDataCreateArgs<ExtArgs>>): Prisma.Prisma__ProcessedDataClient<runtime.Types.Result.GetResult<Prisma.$ProcessedDataPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProcessedData.
   * @param {ProcessedDataCreateManyArgs} args - Arguments to create many ProcessedData.
   * @example
   * // Create many ProcessedData
   * const processedData = await prisma.processedData.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProcessedDataCreateManyArgs>(args?: Prisma.SelectSubset<T, ProcessedDataCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProcessedData and returns the data saved in the database.
   * @param {ProcessedDataCreateManyAndReturnArgs} args - Arguments to create many ProcessedData.
   * @example
   * // Create many ProcessedData
   * const processedData = await prisma.processedData.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProcessedData and only return the `id`
   * const processedDataWithIdOnly = await prisma.processedData.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProcessedDataCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProcessedDataCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProcessedDataPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProcessedData.
   * @param {ProcessedDataDeleteArgs} args - Arguments to delete one ProcessedData.
   * @example
   * // Delete one ProcessedData
   * const ProcessedData = await prisma.processedData.delete({
   *   where: {
   *     // ... filter to delete one ProcessedData
   *   }
   * })
   * 
   */
  delete<T extends ProcessedDataDeleteArgs>(args: Prisma.SelectSubset<T, ProcessedDataDeleteArgs<ExtArgs>>): Prisma.Prisma__ProcessedDataClient<runtime.Types.Result.GetResult<Prisma.$ProcessedDataPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProcessedData.
   * @param {ProcessedDataUpdateArgs} args - Arguments to update one ProcessedData.
   * @example
   * // Update one ProcessedData
   * const processedData = await prisma.processedData.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProcessedDataUpdateArgs>(args: Prisma.SelectSubset<T, ProcessedDataUpdateArgs<ExtArgs>>): Prisma.Prisma__ProcessedDataClient<runtime.Types.Result.GetResult<Prisma.$ProcessedDataPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProcessedData.
   * @param {ProcessedDataDeleteManyArgs} args - Arguments to filter ProcessedData to delete.
   * @example
   * // Delete a few ProcessedData
   * const { count } = await prisma.processedData.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProcessedDataDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProcessedDataDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProcessedData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcessedDataUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProcessedData
   * const processedData = await prisma.processedData.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProcessedDataUpdateManyArgs>(args: Prisma.SelectSubset<T, ProcessedDataUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProcessedData and returns the data updated in the database.
   * @param {ProcessedDataUpdateManyAndReturnArgs} args - Arguments to update many ProcessedData.
   * @example
   * // Update many ProcessedData
   * const processedData = await prisma.processedData.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProcessedData and only return the `id`
   * const processedDataWithIdOnly = await prisma.processedData.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProcessedDataUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProcessedDataUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProcessedDataPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProcessedData.
   * @param {ProcessedDataUpsertArgs} args - Arguments to update or create a ProcessedData.
   * @example
   * // Update or create a ProcessedData
   * const processedData = await prisma.processedData.upsert({
   *   create: {
   *     // ... data to create a ProcessedData
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProcessedData we want to update
   *   }
   * })
   */
  upsert<T extends ProcessedDataUpsertArgs>(args: Prisma.SelectSubset<T, ProcessedDataUpsertArgs<ExtArgs>>): Prisma.Prisma__ProcessedDataClient<runtime.Types.Result.GetResult<Prisma.$ProcessedDataPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProcessedData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcessedDataCountArgs} args - Arguments to filter ProcessedData to count.
   * @example
   * // Count the number of ProcessedData
   * const count = await prisma.processedData.count({
   *   where: {
   *     // ... the filter for the ProcessedData we want to count
   *   }
   * })
  **/
  count<T extends ProcessedDataCountArgs>(
    args?: Prisma.Subset<T, ProcessedDataCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProcessedDataCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProcessedData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcessedDataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProcessedDataAggregateArgs>(args: Prisma.Subset<T, ProcessedDataAggregateArgs>): Prisma.PrismaPromise<GetProcessedDataAggregateType<T>>

  /**
   * Group by ProcessedData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcessedDataGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProcessedDataGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProcessedDataGroupByArgs['orderBy'] }
      : { orderBy?: ProcessedDataGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProcessedDataGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProcessedDataGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProcessedData model
 */
readonly fields: ProcessedDataFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProcessedData.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProcessedDataClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProcessedData model
 */
export interface ProcessedDataFieldRefs {
  readonly id: Prisma.FieldRef<"ProcessedData", 'String'>
  readonly analysisRequestId: Prisma.FieldRef<"ProcessedData", 'String'>
  readonly userId: Prisma.FieldRef<"ProcessedData", 'String'>
  readonly chain: Prisma.FieldRef<"ProcessedData", 'String'>
  readonly address: Prisma.FieldRef<"ProcessedData", 'String'>
  readonly score: Prisma.FieldRef<"ProcessedData", 'Int'>
  readonly confidence: Prisma.FieldRef<"ProcessedData", 'Float'>
  readonly reasoning: Prisma.FieldRef<"ProcessedData", 'String'>
  readonly positiveFactors: Prisma.FieldRef<"ProcessedData", 'Json'>
  readonly riskFactors: Prisma.FieldRef<"ProcessedData", 'Json'>
  readonly modelVersion: Prisma.FieldRef<"ProcessedData", 'String'>
  readonly promptVersion: Prisma.FieldRef<"ProcessedData", 'String'>
  readonly tokensUsed: Prisma.FieldRef<"ProcessedData", 'Int'>
  readonly cost: Prisma.FieldRef<"ProcessedData", 'Float'>
  readonly inferenceDurationMs: Prisma.FieldRef<"ProcessedData", 'Int'>
  readonly walletContextHash: Prisma.FieldRef<"ProcessedData", 'String'>
  readonly validUntil: Prisma.FieldRef<"ProcessedData", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ProcessedData", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ProcessedData findUnique
 */
export type ProcessedDataFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcessedData
   */
  select?: Prisma.ProcessedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProcessedData
   */
  omit?: Prisma.ProcessedDataOmit<ExtArgs> | null
  /**
   * Filter, which ProcessedData to fetch.
   */
  where: Prisma.ProcessedDataWhereUniqueInput
}

/**
 * ProcessedData findUniqueOrThrow
 */
export type ProcessedDataFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcessedData
   */
  select?: Prisma.ProcessedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProcessedData
   */
  omit?: Prisma.ProcessedDataOmit<ExtArgs> | null
  /**
   * Filter, which ProcessedData to fetch.
   */
  where: Prisma.ProcessedDataWhereUniqueInput
}

/**
 * ProcessedData findFirst
 */
export type ProcessedDataFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcessedData
   */
  select?: Prisma.ProcessedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProcessedData
   */
  omit?: Prisma.ProcessedDataOmit<ExtArgs> | null
  /**
   * Filter, which ProcessedData to fetch.
   */
  where?: Prisma.ProcessedDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProcessedData to fetch.
   */
  orderBy?: Prisma.ProcessedDataOrderByWithRelationInput | Prisma.ProcessedDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProcessedData.
   */
  cursor?: Prisma.ProcessedDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProcessedData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProcessedData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProcessedData.
   */
  distinct?: Prisma.ProcessedDataScalarFieldEnum | Prisma.ProcessedDataScalarFieldEnum[]
}

/**
 * ProcessedData findFirstOrThrow
 */
export type ProcessedDataFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcessedData
   */
  select?: Prisma.ProcessedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProcessedData
   */
  omit?: Prisma.ProcessedDataOmit<ExtArgs> | null
  /**
   * Filter, which ProcessedData to fetch.
   */
  where?: Prisma.ProcessedDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProcessedData to fetch.
   */
  orderBy?: Prisma.ProcessedDataOrderByWithRelationInput | Prisma.ProcessedDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProcessedData.
   */
  cursor?: Prisma.ProcessedDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProcessedData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProcessedData.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProcessedData.
   */
  distinct?: Prisma.ProcessedDataScalarFieldEnum | Prisma.ProcessedDataScalarFieldEnum[]
}

/**
 * ProcessedData findMany
 */
export type ProcessedDataFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcessedData
   */
  select?: Prisma.ProcessedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProcessedData
   */
  omit?: Prisma.ProcessedDataOmit<ExtArgs> | null
  /**
   * Filter, which ProcessedData to fetch.
   */
  where?: Prisma.ProcessedDataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProcessedData to fetch.
   */
  orderBy?: Prisma.ProcessedDataOrderByWithRelationInput | Prisma.ProcessedDataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProcessedData.
   */
  cursor?: Prisma.ProcessedDataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProcessedData from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProcessedData.
   */
  skip?: number
  distinct?: Prisma.ProcessedDataScalarFieldEnum | Prisma.ProcessedDataScalarFieldEnum[]
}

/**
 * ProcessedData create
 */
export type ProcessedDataCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcessedData
   */
  select?: Prisma.ProcessedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProcessedData
   */
  omit?: Prisma.ProcessedDataOmit<ExtArgs> | null
  /**
   * The data needed to create a ProcessedData.
   */
  data: Prisma.XOR<Prisma.ProcessedDataCreateInput, Prisma.ProcessedDataUncheckedCreateInput>
}

/**
 * ProcessedData createMany
 */
export type ProcessedDataCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProcessedData.
   */
  data: Prisma.ProcessedDataCreateManyInput | Prisma.ProcessedDataCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProcessedData createManyAndReturn
 */
export type ProcessedDataCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcessedData
   */
  select?: Prisma.ProcessedDataSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProcessedData
   */
  omit?: Prisma.ProcessedDataOmit<ExtArgs> | null
  /**
   * The data used to create many ProcessedData.
   */
  data: Prisma.ProcessedDataCreateManyInput | Prisma.ProcessedDataCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProcessedData update
 */
export type ProcessedDataUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcessedData
   */
  select?: Prisma.ProcessedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProcessedData
   */
  omit?: Prisma.ProcessedDataOmit<ExtArgs> | null
  /**
   * The data needed to update a ProcessedData.
   */
  data: Prisma.XOR<Prisma.ProcessedDataUpdateInput, Prisma.ProcessedDataUncheckedUpdateInput>
  /**
   * Choose, which ProcessedData to update.
   */
  where: Prisma.ProcessedDataWhereUniqueInput
}

/**
 * ProcessedData updateMany
 */
export type ProcessedDataUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProcessedData.
   */
  data: Prisma.XOR<Prisma.ProcessedDataUpdateManyMutationInput, Prisma.ProcessedDataUncheckedUpdateManyInput>
  /**
   * Filter which ProcessedData to update
   */
  where?: Prisma.ProcessedDataWhereInput
  /**
   * Limit how many ProcessedData to update.
   */
  limit?: number
}

/**
 * ProcessedData updateManyAndReturn
 */
export type ProcessedDataUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcessedData
   */
  select?: Prisma.ProcessedDataSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProcessedData
   */
  omit?: Prisma.ProcessedDataOmit<ExtArgs> | null
  /**
   * The data used to update ProcessedData.
   */
  data: Prisma.XOR<Prisma.ProcessedDataUpdateManyMutationInput, Prisma.ProcessedDataUncheckedUpdateManyInput>
  /**
   * Filter which ProcessedData to update
   */
  where?: Prisma.ProcessedDataWhereInput
  /**
   * Limit how many ProcessedData to update.
   */
  limit?: number
}

/**
 * ProcessedData upsert
 */
export type ProcessedDataUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcessedData
   */
  select?: Prisma.ProcessedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProcessedData
   */
  omit?: Prisma.ProcessedDataOmit<ExtArgs> | null
  /**
   * The filter to search for the ProcessedData to update in case it exists.
   */
  where: Prisma.ProcessedDataWhereUniqueInput
  /**
   * In case the ProcessedData found by the `where` argument doesn't exist, create a new ProcessedData with this data.
   */
  create: Prisma.XOR<Prisma.ProcessedDataCreateInput, Prisma.ProcessedDataUncheckedCreateInput>
  /**
   * In case the ProcessedData was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProcessedDataUpdateInput, Prisma.ProcessedDataUncheckedUpdateInput>
}

/**
 * ProcessedData delete
 */
export type ProcessedDataDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcessedData
   */
  select?: Prisma.ProcessedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProcessedData
   */
  omit?: Prisma.ProcessedDataOmit<ExtArgs> | null
  /**
   * Filter which ProcessedData to delete.
   */
  where: Prisma.ProcessedDataWhereUniqueInput
}

/**
 * ProcessedData deleteMany
 */
export type ProcessedDataDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProcessedData to delete
   */
  where?: Prisma.ProcessedDataWhereInput
  /**
   * Limit how many ProcessedData to delete.
   */
  limit?: number
}

/**
 * ProcessedData without action
 */
export type ProcessedDataDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcessedData
   */
  select?: Prisma.ProcessedDataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProcessedData
   */
  omit?: Prisma.ProcessedDataOmit<ExtArgs> | null
}
