
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  ADMIN: 'ADMIN',
  USER: 'USER'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const Plan = {
  FREE_TIER: 'FREE_TIER',
  PRO: 'PRO'
} as const

export type Plan = (typeof Plan)[keyof typeof Plan]


export const SubscriptionStatus = {
  active: 'active',
  past_due: 'past_due',
  canceled: 'canceled',
  trialing: 'trialing'
} as const

export type SubscriptionStatus = (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus]
